package rs.ac.bg.etf.pp1.util;

import rs.ac.bg.etf.pp1.ast.*;

public abstract class TreeVisitor extends VisitorAdaptor {
    public void visit(MJExpression tree) { tree.childrenAccept(this); }
    public void visit(MJNoExpression tree) { tree.childrenAccept(this); }
    public void visit(MJExpressionOption tree) { tree.childrenAccept(this); }
    public void visit(MJLeftHandSideArrayAccess tree) { tree.childrenAccept(this); }
    public void visit(MJLeftHandSideFieldAccress tree) { tree.childrenAccept(this); }
    public void visit(MJLeftHandSideName tree) { tree.childrenAccept(this); }
    public void visit(MJAssignment tree) { tree.childrenAccept(this); }
    public void visit(MJAssignmentExpression tree) { tree.childrenAccept(this); }
    public void visit(MJConditionalExpression tree) { tree.childrenAccept(this); }
    public void visit(MJTernaryOperation tree) { tree.childrenAccept(this); }
    public void visit(MJConditionalOrExpression tree) { tree.childrenAccept(this); }
    public void visit(MJDisjunction tree) { tree.childrenAccept(this); }
    public void visit(MJConditionalAndExpression tree) { tree.childrenAccept(this); }
    public void visit(MJConjuction tree) { tree.childrenAccept(this); }
    public void visit(MJEqualityExpression tree) { tree.childrenAccept(this); }
    public void visit(MJNotEqual tree) { tree.childrenAccept(this); }
    public void visit(MJEqual tree) { tree.childrenAccept(this); }
    public void visit(MJRelationalExpression tree) { tree.childrenAccept(this); }
    public void visit(MJGreaterThanOrEqualTo tree) { tree.childrenAccept(this); }
    public void visit(MJLessThanOrEqualTo tree) { tree.childrenAccept(this); }
    public void visit(MJGreaterThan tree) { tree.childrenAccept(this); }
    public void visit(MJLessThan tree) { tree.childrenAccept(this); }
    public void visit(MJAdditiveExpression tree) { tree.childrenAccept(this); }
    public void visit(MJSubtraction tree) { tree.childrenAccept(this); }
    public void visit(MJAddition tree) { tree.childrenAccept(this); }
    public void visit(MJMultiplicativeExpression tree) { tree.childrenAccept(this); }
    public void visit(MJModulo tree) { tree.childrenAccept(this); }
    public void visit(MJDivision tree) { tree.childrenAccept(this); }
    public void visit(MJMultiplication tree) { tree.childrenAccept(this); }
    public void visit(MJUnaryExpression tree) { tree.childrenAccept(this); }
    public void visit(MJPostfixExpression tree) { tree.childrenAccept(this); }
    public void visit(MJNegation tree) { tree.childrenAccept(this); }
    public void visit(MJPostdecrement tree) { tree.childrenAccept(this); }
    public void visit(MJPostincrement tree) { tree.childrenAccept(this); }
    public void visit(MJPostdecrementExpression tree) { tree.childrenAccept(this); }
    public void visit(MJPostincrementExpression tree) { tree.childrenAccept(this); }
    public void visit(MJNameExpression tree) { tree.childrenAccept(this); }
    public void visit(MJPrimaryExpression tree) { tree.childrenAccept(this); }
    public void visit(MJQualifiedArrayAccess tree) { tree.childrenAccept(this); }
    public void visit(MJArrayAccess tree) { tree.childrenAccept(this); }
    public void visit(MJPrintConst tree) { tree.childrenAccept(this); }
    public void visit(MJPrint tree) { tree.childrenAccept(this); }
    public void visit(MJRead tree) { tree.childrenAccept(this); }
    public void visit(MJQualifiedMethodInvocation tree) { tree.childrenAccept(this); }
    public void visit(MJMethodInvocation tree) { tree.childrenAccept(this); }
    public void visit(MJLengthFieldAcces tree) { tree.childrenAccept(this); }
    public void visit(MJFieldAccess tree) { tree.childrenAccept(this); }
    public void visit(MJArrayCreation tree) { tree.childrenAccept(this); }
    public void visit(MJNextArgument tree) { tree.childrenAccept(this); }
    public void visit(MJArgument tree) { tree.childrenAccept(this); }
    public void visit(MJNoArgumentList tree) { tree.childrenAccept(this); }
    public void visit(MJArgumentList tree) { tree.childrenAccept(this); }
    public void visit(MJClassInstanceCreation tree) { tree.childrenAccept(this); }
    public void visit(MJPrimaryArrayAccess tree) { tree.childrenAccept(this); }
    public void visit(MJPrimaryMethodInvocation tree) { tree.childrenAccept(this); }
    public void visit(MJPrimaryFieldAccess tree) { tree.childrenAccept(this); }
    public void visit(MJParenthesisedExpression tree) { tree.childrenAccept(this); }
    public void visit(MJThis tree) { tree.childrenAccept(this); }
    public void visit(MJPrimaryLiteral tree) { tree.childrenAccept(this); }
    public void visit(MJPrimaryArrayCreationExpression tree) { tree.childrenAccept(this); }
    public void visit(MJPrimaryClassInstanceCreationExpression tree) { tree.childrenAccept(this); }
    public void visit(MJPrimaryNoNewArray tree) { tree.childrenAccept(this); }
    public void visit(MJReturn tree) { tree.childrenAccept(this); }
    public void visit(MJContinue tree) { tree.childrenAccept(this); }
    public void visit(MJBreak tree) { tree.childrenAccept(this); }
    public void visit(MJNextStatementExpression tree) { tree.childrenAccept(this); }
    public void visit(MJFirstStatementExpression tree) { tree.childrenAccept(this); }
    public void visit(MJForUpdate tree) { tree.childrenAccept(this); }
    public void visit(MJNoForUpdate tree) { tree.childrenAccept(this); }
    public void visit(MJForUpdateOpt tree) { tree.childrenAccept(this); }
    public void visit(MJForInit tree) { tree.childrenAccept(this); }
    public void visit(MJNoForInit tree) { tree.childrenAccept(this); }
    public void visit(MJForInitOpt tree) { tree.childrenAccept(this); }
    public void visit(MJForNoShortIf tree) { tree.childrenAccept(this); }
    public void visit(MJFor tree) { tree.childrenAccept(this); }
    public void visit(MJSwitchLabelValueError tree) { tree.childrenAccept(this); }
    public void visit(MJSwitchLabelValue tree) { tree.childrenAccept(this); }
    public void visit(MJSwitchLabel tree) { tree.childrenAccept(this); }
    public void visit(MJNextSwitchLabel tree) { tree.childrenAccept(this); }
    public void visit(MJFirstSwitchLabel tree) { tree.childrenAccept(this); }
    public void visit(MJSwitchStatementsGroup tree) { tree.childrenAccept(this); }
    public void visit(MJNextSwitchStatementsGroups tree) { tree.childrenAccept(this); }
    public void visit(MJFirstSwitchStatementGroups tree) { tree.childrenAccept(this); }
    public void visit(MJEmptySwitchBlock tree) { tree.childrenAccept(this); }
    public void visit(MJSwitchStatements tree) { tree.childrenAccept(this); }
    public void visit(MJSwitch tree) { tree.childrenAccept(this); }
    public void visit(MJIfConditionError tree) { tree.childrenAccept(this); }
    public void visit(MJIfCondition tree) { tree.childrenAccept(this); }
    public void visit(MJIfThenElseNoShortIf tree) { tree.childrenAccept(this); }
    public void visit(MJIfThenElse tree) { tree.childrenAccept(this); }
    public void visit(MJIfThen tree) { tree.childrenAccept(this); }
    public void visit(MJClassInstanceCreationStatementExpression tree) { tree.childrenAccept(this); }
    public void visit(MJMethodInvocationStatementExpression tree) { tree.childrenAccept(this); }
    public void visit(MJPostdecrementStatementExpression tree) { tree.childrenAccept(this); }
    public void visit(MJPostincrementStatementExpression tree) { tree.childrenAccept(this); }
    public void visit(MJAssignmentStatementExpression tree) { tree.childrenAccept(this); }
    public void visit(MJStatementExpression tree) { tree.childrenAccept(this); }
    public void visit(MJEmpty tree) { tree.childrenAccept(this); }
    public void visit(MJStatementError tree) { tree.childrenAccept(this); }
    public void visit(MJReturnStatement tree) { tree.childrenAccept(this); }
    public void visit(MJContinueStatement tree) { tree.childrenAccept(this); }
    public void visit(MJBreakStatement tree) { tree.childrenAccept(this); }
    public void visit(MJSwitchStatement tree) { tree.childrenAccept(this); }
    public void visit(MJExpressionStatement tree) { tree.childrenAccept(this); }
    public void visit(MJEmptyStatement tree) { tree.childrenAccept(this); }
    public void visit(MJStatementBlock tree) { tree.childrenAccept(this); }
    public void visit(MJForStatementNoShortIf tree) { tree.childrenAccept(this); }
    public void visit(MJIfThenElseStatementNoShortIf tree) { tree.childrenAccept(this); }
    public void visit(MJStatementWithoutTrailingSubstatementNoShortIf tree) { tree.childrenAccept(this); }
    public void visit(MJForStatement tree) { tree.childrenAccept(this); }
    public void visit(MJIfThenElseStatement tree) { tree.childrenAccept(this); }
    public void visit(MJIfThenStatement tree) { tree.childrenAccept(this); }
    public void visit(MJStatementWithoutTrailingSubstatement tree) { tree.childrenAccept(this); }
    public void visit(MJBlockStatement tree) { tree.childrenAccept(this); }
    public void visit(MJNextBlockStatement tree) { tree.childrenAccept(this); }
    public void visit(MJFirstBlockStatement tree) { tree.childrenAccept(this); }
    public void visit(MJNoBlockStatements tree) { tree.childrenAccept(this); }
    public void visit(MJBlockStatements tree) { tree.childrenAccept(this); }
    public void visit(MJBlock tree) { tree.childrenAccept(this); }
    public void visit(MJMethodVariableError tree) { tree.childrenAccept(this); }
    public void visit(MJMethodVariable tree) { tree.childrenAccept(this); }
    public void visit(MJNextMethodVariable tree) { tree.childrenAccept(this); }
    public void visit(MJFirstMethodVariable tree) { tree.childrenAccept(this); }
    public void visit(MJNoMethodVariables tree) { tree.childrenAccept(this); }
    public void visit(MJMethodVariables tree) { tree.childrenAccept(this); }
    public void visit(MJFormalParameterError tree) { tree.childrenAccept(this); }
    public void visit(MJParameter tree) { tree.childrenAccept(this); }
    public void visit(MJNextFormalParameter tree) { tree.childrenAccept(this); }
    public void visit(MJFormalParameter tree) { tree.childrenAccept(this); }
    public void visit(MJNoFormalParameters tree) { tree.childrenAccept(this); }
    public void visit(MJFormalParameters tree) { tree.childrenAccept(this); }
    public void visit(MJAbstractMethodBody tree) { tree.childrenAccept(this); }
    public void visit(MJMethodBody tree) { tree.childrenAccept(this); }
    public void visit(MJVoidMethodSignature tree) { tree.childrenAccept(this); }
    public void visit(MJTypeMethodSignature tree) { tree.childrenAccept(this); }
    public void visit(MJMethodDeclaration tree) { tree.childrenAccept(this); }
    public void visit(MJMethodDeclarationError tree) { tree.childrenAccept(this); }
    public void visit(MJMethodDeclarationElement tree) { tree.childrenAccept(this); }
    public void visit(MJNextMethod tree) { tree.childrenAccept(this); }
    public void visit(MJMethod tree) { tree.childrenAccept(this); }
    public void visit(MJNoMethods tree) { tree.childrenAccept(this); }
    public void visit(MJMethodsOption tree) { tree.childrenAccept(this); }
    public void visit(MJMethodsBlock tree) { tree.childrenAccept(this); }
    public void visit(MJNoMethodsBlock tree) { tree.childrenAccept(this); }
    public void visit(MJMethodsBlockOption tree) { tree.childrenAccept(this); }
    public void visit(MJArrayName tree) { tree.childrenAccept(this); }
    public void visit(MJVariableName tree) { tree.childrenAccept(this); }
    public void visit(MJVariableDeclarationError tree) { tree.childrenAccept(this); }
    public void visit(MJConstant tree) { tree.childrenAccept(this); }
    public void visit(MJVariable tree) { tree.childrenAccept(this); }
    public void visit(MJNextVariableDeclarator tree) { tree.childrenAccept(this); }
    public void visit(MJVariableDeclarator tree) { tree.childrenAccept(this); }
    public void visit(MJFieldDeclaration tree) { tree.childrenAccept(this); }
    public void visit(MJMemberDeclarationError tree) { tree.childrenAccept(this); }
    public void visit(MJClassFieldDeclaration tree) { tree.childrenAccept(this); }
    public void visit(MJNextFieldDeclaration tree) { tree.childrenAccept(this); }
    public void visit(MJMemberDeclaration tree) { tree.childrenAccept(this); }
    public void visit(MJNoFieldDeclarations tree) { tree.childrenAccept(this); }
    public void visit(MJMemberDeclarations tree) { tree.childrenAccept(this); }
    public void visit(MJClassBody tree) { tree.childrenAccept(this); }
    public void visit(MJSuperError tree) { tree.childrenAccept(this); }
    public void visit(MJNoSuperClass tree) { tree.childrenAccept(this); }
    public void visit(MJSuper tree) { tree.childrenAccept(this); }
    public void visit(MJClassDeclaration tree) { tree.childrenAccept(this); }
    public void visit(MJEnumEntryError tree) { tree.childrenAccept(this); }
    public void visit(MJEnumEntryWithValue tree) { tree.childrenAccept(this); }
    public void visit(MJSimpleEnumEntry tree) { tree.childrenAccept(this); }
    public void visit(MJNextEnumEntry tree) { tree.childrenAccept(this); }
    public void visit(MJEnumEntry tree) { tree.childrenAccept(this); }
    public void visit(MJNoEnumEntries tree) { tree.childrenAccept(this); }
    public void visit(MJEnumEntries tree) { tree.childrenAccept(this); }
    public void visit(MJEnumBody tree) { tree.childrenAccept(this); }
    public void visit(MJEnumDeclaration tree) { tree.childrenAccept(this); }
    public void visit(MJAbstractModifier tree) { tree.childrenAccept(this); }
    public void visit(MJConstModifier tree) { tree.childrenAccept(this); }
    public void visit(MJNextModifier tree) { tree.childrenAccept(this); }
    public void visit(MJFirstModifier tree) { tree.childrenAccept(this); }
    public void visit(MJNoModifiers tree) { tree.childrenAccept(this); }
    public void visit(MJModifiersOption tree) { tree.childrenAccept(this); }
    public void visit(MJStaticMethodDeclarationError tree) { tree.childrenAccept(this); }
    public void visit(MJProgramMethod tree) { tree.childrenAccept(this); }
    public void visit(MJNextStaticMethod tree) { tree.childrenAccept(this); }
    public void visit(MJStaticMethod tree) { tree.childrenAccept(this); }
    public void visit(MJNoStaticMethods tree) { tree.childrenAccept(this); }
    public void visit(MJStaticMethodsOption tree) { tree.childrenAccept(this); }
    public void visit(MJStaticMethodsBlock tree) { tree.childrenAccept(this); }
    public void visit(MJProgramDeclarationError tree) { tree.childrenAccept(this); }
    public void visit(MJProgramEnum tree) { tree.childrenAccept(this); }
    public void visit(MJProgramClass tree) { tree.childrenAccept(this); }
    public void visit(MJProgramVariable tree) { tree.childrenAccept(this); }
    public void visit(MJNextProgramDeclarations tree) { tree.childrenAccept(this); }
    public void visit(MJProgramDeclaration tree) { tree.childrenAccept(this); }
    public void visit(MJNoProgramDeclarations tree) { tree.childrenAccept(this); }
    public void visit(MJProgramDeclarations tree) { tree.childrenAccept(this); }
    public void visit(MJProgram tree) { tree.childrenAccept(this); }
    public void visit(MJLength tree) { tree.childrenAccept(this); }
    public void visit(MJQualifiedName tree) { tree.childrenAccept(this); }
    public void visit(MJSimpleName tree) { tree.childrenAccept(this); }
    public void visit(MJNameQualified tree) { tree.childrenAccept(this); }
    public void visit(MJNameSimple tree) { tree.childrenAccept(this); }
    public void visit(MJType tree) { tree.childrenAccept(this); }
    public void visit(MJCharacterLiteral tree) { tree.childrenAccept(this); }
    public void visit(MJBooleanLiteral tree) { tree.childrenAccept(this); }
    public void visit(MJIntegerLiteral tree) { tree.childrenAccept(this); }
    public void visit(MJNullLiteral tree) { tree.childrenAccept(this); }
    public void visit(MJConstLiteral tree) { tree.childrenAccept(this); }
}
