package rs.ac.bg.etf.pp1.codegen;

@SuppressWarnings("SpellCheckingInspection")
public interface Bytecodes {
    int
        load        =  1,
        load_n      =  2,
        load_1      =  3,
        load_2      =  4,
        load_3      =  5,
        store       =  6,
        store_0     =  7,
        store_1     =  8,
        store_2     =  9,
        store_3     = 10,
        getstatic   = 11,
        putstatic   = 12,
        getfield    = 13,
        putfield    = 14,
        const_0     = 15,
        const_1     = 16,
        const_2     = 17,
        const_3     = 18,
        const_4     = 19,
        const_5     = 20,
        const_m1    = 21,
        const_      = 22,
        add         = 23,
        sub         = 24,
        mul         = 25,
        div         = 26,
        rem         = 27,
        neg         = 28,
        shl         = 29,
        shr         = 30,
        inc         = 31,
        new_        = 32,
        newarray    = 33,
        aload       = 34,
        astore      = 35,
        baload      = 36,
        bastore     = 37,
        arraylength = 38,
        pop         = 39,
        dup         = 40,
        dup2        = 41,
        jmp         = 42,
        ifeq        = 43,
        ifne        = 44,
        iflt        = 45,
        ifle        = 46,
        ifgt        = 47,
        ifge        = 48,
        call        = 49,
        return_     = 50,
        enter       = 51,
        exit        = 52,
        read        = 53,
        print       = 54,
        bread       = 55,
        bprint      = 56,
        trap        = 57,
        invokevirtual = 58,
        dup_x1      = 59,
        dup_x2      = 60;

    int
        jcc = ifeq,
        eq = 0,
        ne = 1,
        lt = 2,
        le = 3,
        gt = 4,
        ge = 5;

    int dontjmp = -1;

    int
        intCode = 0,
        charCode = 1,
        byteCode = 2,
        objectCode = 3,
        voidCode = 4,
        TypeCodeCount = 5;
}
